name: Linter
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  trunk-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ... other setup steps
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
      # ... other CI steps
